#!/bin/sh

set -e

chroot_dir=$AUTOPKGTEST_TMP/chroot
start_date=20171001T000000Z
end_date=20171210T000000Z

case "$(lsb_release -s -i)" in
    Debian)
        dpkg-buildpackage -us -uc 2>&1
        debootstrap sid $chroot_dir "http://snapshot.debian.org/archive/debian/$start_date/ unstable main"
        mount --bind /dev/pts $chroot_dir/dev/pts
        sed -i 's/^deb /deb [check-valid-until=no] /' $chroot_dir/etc/apt/sources.list
        chroot $chroot_dir apt-get update
        # install u-u to pull in dependencies and mark python3.5-minimal
        # because otherwise u-u autoremoves it while running python3.5 code
        chroot $chroot_dir apt-get install -y unattended-upgrades python3.5-minimal
        # add package set with many dependencies
        chroot $chroot_dir apt-get install -y xfce4
        chroot $chroot_dir apt-mark showmanual > $chroot_dir/tmp/manual
        cp ../unattended-upgrades_*.deb $chroot_dir/tmp/
        chroot $chroot_dir bash -c 'dpkg -i /tmp/unattended-upgrades_*deb' 2>&1
        sed -i "s/$start_date/$end_date/" $chroot_dir/etc/apt/sources.list
        chroot $chroot_dir apt-get update
        chroot $chroot_dir unattended-upgrade --verbose
        echo "new packages marked as manually installed (should be none): "
        chroot $chroot_dir apt-mark showmanual | diff $chroot_dir/tmp/manual -
        # cleanup
        umount $chroot_dir/dev/pts
        rm -rf $chroot_dir
        ;;
esac
