#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

db_input medium unattended-upgrades/enable_auto_updates || true
db_input medium unattended-upgrades/origins_pattern || true
db_go
